// Auto-generated ADN economy constants
export const ADN_ECONOMY_CONTROLS = {
  "base_xp_to_next_level": 120,
  "xp_exponent": 1.43,
  "base_tap_reward": 1,
  "tap_reward_growth_level": 0.04,
  "base_max_energy": 500,
  "energy_per_player_level": 30,
  "base_energy_regen_min": 8,
  "regen_step_levels": 5,
  "regen_increase_step": 1,
  "base_offline_cap_hours": 3,
  "offline_cap_hours_level": 0.25,
  "offline_cap_max_hours": 12,
  "base_passive_cap_hour": 250,
  "passive_cap_growth_level": 0.18,
  "base_airdrop_weight_1k_earned": 2,
  "airdrop_weight_growth_level": 0.015
} as const;

export const ADN_LEVELS = [
  {
    "level": 1,
    "xp_to_next": 120,
    "cumulative_xp": 120,
    "tap_reward": 1.0,
    "max_energy": 500,
    "regen_per_min": 8,
    "offline_cap_hours": 3.0,
    "passive_cap_per_hour": 250,
    "airdrop_weight_per_1000": 2.0
  },
  {
    "level": 2,
    "xp_to_next": 323,
    "cumulative_xp": 443,
    "tap_reward": 1.04,
    "max_energy": 530,
    "regen_per_min": 8,
    "offline_cap_hours": 3.25,
    "passive_cap_per_hour": 295,
    "airdrop_weight_per_1000": 2.03
  },
  {
    "level": 3,
    "xp_to_next": 577,
    "cumulative_xp": 1020,
    "tap_reward": 1.08,
    "max_energy": 560,
    "regen_per_min": 8,
    "offline_cap_hours": 3.5,
    "passive_cap_per_hour": 348,
    "airdrop_weight_per_1000": 2.06
  },
  {
    "level": 4,
    "xp_to_next": 871,
    "cumulative_xp": 1891,
    "tap_reward": 1.12,
    "max_energy": 590,
    "regen_per_min": 8,
    "offline_cap_hours": 3.75,
    "passive_cap_per_hour": 411,
    "airdrop_weight_per_1000": 2.09
  },
  {
    "level": 5,
    "xp_to_next": 1199,
    "cumulative_xp": 3090,
    "tap_reward": 1.17,
    "max_energy": 620,
    "regen_per_min": 8,
    "offline_cap_hours": 4.0,
    "passive_cap_per_hour": 485,
    "airdrop_weight_per_1000": 2.12
  },
  {
    "level": 6,
    "xp_to_next": 1556,
    "cumulative_xp": 4646,
    "tap_reward": 1.22,
    "max_energy": 650,
    "regen_per_min": 9,
    "offline_cap_hours": 4.25,
    "passive_cap_per_hour": 572,
    "airdrop_weight_per_1000": 2.15
  },
  {
    "level": 7,
    "xp_to_next": 1939,
    "cumulative_xp": 6585,
    "tap_reward": 1.27,
    "max_energy": 680,
    "regen_per_min": 9,
    "offline_cap_hours": 4.5,
    "passive_cap_per_hour": 675,
    "airdrop_weight_per_1000": 2.19
  },
  {
    "level": 8,
    "xp_to_next": 2347,
    "cumulative_xp": 8932,
    "tap_reward": 1.32,
    "max_energy": 710,
    "regen_per_min": 9,
    "offline_cap_hours": 4.75,
    "passive_cap_per_hour": 796,
    "airdrop_weight_per_1000": 2.22
  },
  {
    "level": 9,
    "xp_to_next": 2778,
    "cumulative_xp": 11710,
    "tap_reward": 1.37,
    "max_energy": 740,
    "regen_per_min": 9,
    "offline_cap_hours": 5.0,
    "passive_cap_per_hour": 940,
    "airdrop_weight_per_1000": 2.25
  },
  {
    "level": 10,
    "xp_to_next": 3230,
    "cumulative_xp": 14940,
    "tap_reward": 1.42,
    "max_energy": 770,
    "regen_per_min": 9,
    "offline_cap_hours": 5.25,
    "passive_cap_per_hour": 1109,
    "airdrop_weight_per_1000": 2.29
  },
  {
    "level": 11,
    "xp_to_next": 3701,
    "cumulative_xp": 18641,
    "tap_reward": 1.48,
    "max_energy": 800,
    "regen_per_min": 10,
    "offline_cap_hours": 5.5,
    "passive_cap_per_hour": 1308,
    "airdrop_weight_per_1000": 2.32
  },
  {
    "level": 12,
    "xp_to_next": 4192,
    "cumulative_xp": 22833,
    "tap_reward": 1.54,
    "max_energy": 830,
    "regen_per_min": 10,
    "offline_cap_hours": 5.75,
    "passive_cap_per_hour": 1544,
    "airdrop_weight_per_1000": 2.36
  },
  {
    "level": 13,
    "xp_to_next": 4700,
    "cumulative_xp": 27533,
    "tap_reward": 1.6,
    "max_energy": 860,
    "regen_per_min": 10,
    "offline_cap_hours": 6.0,
    "passive_cap_per_hour": 1822,
    "airdrop_weight_per_1000": 2.39
  },
  {
    "level": 14,
    "xp_to_next": 5226,
    "cumulative_xp": 32759,
    "tap_reward": 1.67,
    "max_energy": 890,
    "regen_per_min": 10,
    "offline_cap_hours": 6.25,
    "passive_cap_per_hour": 2150,
    "airdrop_weight_per_1000": 2.43
  },
  {
    "level": 15,
    "xp_to_next": 5768,
    "cumulative_xp": 38527,
    "tap_reward": 1.73,
    "max_energy": 920,
    "regen_per_min": 10,
    "offline_cap_hours": 6.5,
    "passive_cap_per_hour": 2537,
    "airdrop_weight_per_1000": 2.46
  },
  {
    "level": 16,
    "xp_to_next": 6325,
    "cumulative_xp": 44852,
    "tap_reward": 1.8,
    "max_energy": 950,
    "regen_per_min": 11,
    "offline_cap_hours": 6.75,
    "passive_cap_per_hour": 2993,
    "airdrop_weight_per_1000": 2.5
  },
  {
    "level": 17,
    "xp_to_next": 6898,
    "cumulative_xp": 51750,
    "tap_reward": 1.87,
    "max_energy": 980,
    "regen_per_min": 11,
    "offline_cap_hours": 7.0,
    "passive_cap_per_hour": 3532,
    "airdrop_weight_per_1000": 2.54
  },
  {
    "level": 18,
    "xp_to_next": 7486,
    "cumulative_xp": 59236,
    "tap_reward": 1.95,
    "max_energy": 1010,
    "regen_per_min": 11,
    "offline_cap_hours": 7.25,
    "passive_cap_per_hour": 4168,
    "airdrop_weight_per_1000": 2.58
  },
  {
    "level": 19,
    "xp_to_next": 8087,
    "cumulative_xp": 67323,
    "tap_reward": 2.03,
    "max_energy": 1040,
    "regen_per_min": 11,
    "offline_cap_hours": 7.5,
    "passive_cap_per_hour": 4918,
    "airdrop_weight_per_1000": 2.61
  },
  {
    "level": 20,
    "xp_to_next": 8703,
    "cumulative_xp": 76026,
    "tap_reward": 2.11,
    "max_energy": 1070,
    "regen_per_min": 11,
    "offline_cap_hours": 7.75,
    "passive_cap_per_hour": 5804,
    "airdrop_weight_per_1000": 2.65
  },
  {
    "level": 21,
    "xp_to_next": 9332,
    "cumulative_xp": 85358,
    "tap_reward": 2.19,
    "max_energy": 1100,
    "regen_per_min": 12,
    "offline_cap_hours": 8.0,
    "passive_cap_per_hour": 6848,
    "airdrop_weight_per_1000": 2.69
  },
  {
    "level": 22,
    "xp_to_next": 9973,
    "cumulative_xp": 95331,
    "tap_reward": 2.28,
    "max_energy": 1130,
    "regen_per_min": 12,
    "offline_cap_hours": 8.25,
    "passive_cap_per_hour": 8081,
    "airdrop_weight_per_1000": 2.73
  },
  {
    "level": 23,
    "xp_to_next": 10628,
    "cumulative_xp": 105959,
    "tap_reward": 2.37,
    "max_energy": 1160,
    "regen_per_min": 12,
    "offline_cap_hours": 8.5,
    "passive_cap_per_hour": 9536,
    "airdrop_weight_per_1000": 2.78
  },
  {
    "level": 24,
    "xp_to_next": 11295,
    "cumulative_xp": 117254,
    "tap_reward": 2.46,
    "max_energy": 1190,
    "regen_per_min": 12,
    "offline_cap_hours": 8.75,
    "passive_cap_per_hour": 11252,
    "airdrop_weight_per_1000": 2.82
  },
  {
    "level": 25,
    "xp_to_next": 11974,
    "cumulative_xp": 129228,
    "tap_reward": 2.56,
    "max_energy": 1220,
    "regen_per_min": 12,
    "offline_cap_hours": 9.0,
    "passive_cap_per_hour": 13277,
    "airdrop_weight_per_1000": 2.86
  },
  {
    "level": 26,
    "xp_to_next": 12665,
    "cumulative_xp": 141893,
    "tap_reward": 2.67,
    "max_energy": 1250,
    "regen_per_min": 13,
    "offline_cap_hours": 9.25,
    "passive_cap_per_hour": 15667,
    "airdrop_weight_per_1000": 2.9
  },
  {
    "level": 27,
    "xp_to_next": 13367,
    "cumulative_xp": 155260,
    "tap_reward": 2.77,
    "max_energy": 1280,
    "regen_per_min": 13,
    "offline_cap_hours": 9.5,
    "passive_cap_per_hour": 18487,
    "airdrop_weight_per_1000": 2.95
  },
  {
    "level": 28,
    "xp_to_next": 14080,
    "cumulative_xp": 169340,
    "tap_reward": 2.88,
    "max_energy": 1310,
    "regen_per_min": 13,
    "offline_cap_hours": 9.75,
    "passive_cap_per_hour": 21815,
    "airdrop_weight_per_1000": 2.99
  },
  {
    "level": 29,
    "xp_to_next": 14805,
    "cumulative_xp": 184145,
    "tap_reward": 3.0,
    "max_energy": 1340,
    "regen_per_min": 13,
    "offline_cap_hours": 10.0,
    "passive_cap_per_hour": 25742,
    "airdrop_weight_per_1000": 3.03
  },
  {
    "level": 30,
    "xp_to_next": 15540,
    "cumulative_xp": 199685,
    "tap_reward": 3.12,
    "max_energy": 1370,
    "regen_per_min": 13,
    "offline_cap_hours": 10.25,
    "passive_cap_per_hour": 30375,
    "airdrop_weight_per_1000": 3.08
  },
  {
    "level": 31,
    "xp_to_next": 16287,
    "cumulative_xp": 215972,
    "tap_reward": 3.24,
    "max_energy": 1400,
    "regen_per_min": 14,
    "offline_cap_hours": 10.5,
    "passive_cap_per_hour": 35843,
    "airdrop_weight_per_1000": 3.13
  },
  {
    "level": 32,
    "xp_to_next": 17043,
    "cumulative_xp": 233015,
    "tap_reward": 3.37,
    "max_energy": 1430,
    "regen_per_min": 14,
    "offline_cap_hours": 10.75,
    "passive_cap_per_hour": 42294,
    "airdrop_weight_per_1000": 3.17
  },
  {
    "level": 33,
    "xp_to_next": 17810,
    "cumulative_xp": 250825,
    "tap_reward": 3.51,
    "max_energy": 1460,
    "regen_per_min": 14,
    "offline_cap_hours": 11.0,
    "passive_cap_per_hour": 49907,
    "airdrop_weight_per_1000": 3.22
  },
  {
    "level": 34,
    "xp_to_next": 18586,
    "cumulative_xp": 269411,
    "tap_reward": 3.65,
    "max_energy": 1490,
    "regen_per_min": 14,
    "offline_cap_hours": 11.25,
    "passive_cap_per_hour": 58891,
    "airdrop_weight_per_1000": 3.27
  },
  {
    "level": 35,
    "xp_to_next": 19373,
    "cumulative_xp": 288784,
    "tap_reward": 3.79,
    "max_energy": 1520,
    "regen_per_min": 14,
    "offline_cap_hours": 11.5,
    "passive_cap_per_hour": 69491,
    "airdrop_weight_per_1000": 3.32
  },
  {
    "level": 36,
    "xp_to_next": 20169,
    "cumulative_xp": 308953,
    "tap_reward": 3.95,
    "max_energy": 1550,
    "regen_per_min": 15,
    "offline_cap_hours": 11.75,
    "passive_cap_per_hour": 81999,
    "airdrop_weight_per_1000": 3.37
  },
  {
    "level": 37,
    "xp_to_next": 20975,
    "cumulative_xp": 329928,
    "tap_reward": 4.1,
    "max_energy": 1580,
    "regen_per_min": 15,
    "offline_cap_hours": 12,
    "passive_cap_per_hour": 96759,
    "airdrop_weight_per_1000": 3.42
  },
  {
    "level": 38,
    "xp_to_next": 21791,
    "cumulative_xp": 351719,
    "tap_reward": 4.27,
    "max_energy": 1610,
    "regen_per_min": 15,
    "offline_cap_hours": 12,
    "passive_cap_per_hour": 114176,
    "airdrop_weight_per_1000": 3.47
  },
  {
    "level": 39,
    "xp_to_next": 22615,
    "cumulative_xp": 374334,
    "tap_reward": 4.44,
    "max_energy": 1640,
    "regen_per_min": 15,
    "offline_cap_hours": 12,
    "passive_cap_per_hour": 134728,
    "airdrop_weight_per_1000": 3.52
  },
  {
    "level": 40,
    "xp_to_next": 23449,
    "cumulative_xp": 397783,
    "tap_reward": 4.62,
    "max_energy": 1670,
    "regen_per_min": 15,
    "offline_cap_hours": 12,
    "passive_cap_per_hour": 158978,
    "airdrop_weight_per_1000": 3.57
  },
  {
    "level": 41,
    "xp_to_next": 24292,
    "cumulative_xp": 422075,
    "tap_reward": 4.8,
    "max_energy": 1700,
    "regen_per_min": 16,
    "offline_cap_hours": 12,
    "passive_cap_per_hour": 187595,
    "airdrop_weight_per_1000": 3.63
  },
  {
    "level": 42,
    "xp_to_next": 25144,
    "cumulative_xp": 447219,
    "tap_reward": 4.99,
    "max_energy": 1730,
    "regen_per_min": 16,
    "offline_cap_hours": 12,
    "passive_cap_per_hour": 221362,
    "airdrop_weight_per_1000": 3.68
  },
  {
    "level": 43,
    "xp_to_next": 26004,
    "cumulative_xp": 473223,
    "tap_reward": 5.19,
    "max_energy": 1760,
    "regen_per_min": 16,
    "offline_cap_hours": 12,
    "passive_cap_per_hour": 261207,
    "airdrop_weight_per_1000": 3.74
  },
  {
    "level": 44,
    "xp_to_next": 26873,
    "cumulative_xp": 500096,
    "tap_reward": 5.4,
    "max_energy": 1790,
    "regen_per_min": 16,
    "offline_cap_hours": 12,
    "passive_cap_per_hour": 308224,
    "airdrop_weight_per_1000": 3.79
  },
  {
    "level": 45,
    "xp_to_next": 27751,
    "cumulative_xp": 527847,
    "tap_reward": 5.62,
    "max_energy": 1820,
    "regen_per_min": 16,
    "offline_cap_hours": 12,
    "passive_cap_per_hour": 363704,
    "airdrop_weight_per_1000": 3.85
  },
  {
    "level": 46,
    "xp_to_next": 28637,
    "cumulative_xp": 556484,
    "tap_reward": 5.84,
    "max_energy": 1850,
    "regen_per_min": 17,
    "offline_cap_hours": 12,
    "passive_cap_per_hour": 429171,
    "airdrop_weight_per_1000": 3.91
  },
  {
    "level": 47,
    "xp_to_next": 29531,
    "cumulative_xp": 586015,
    "tap_reward": 6.07,
    "max_energy": 1880,
    "regen_per_min": 17,
    "offline_cap_hours": 12,
    "passive_cap_per_hour": 506422,
    "airdrop_weight_per_1000": 3.97
  },
  {
    "level": 48,
    "xp_to_next": 30434,
    "cumulative_xp": 616449,
    "tap_reward": 6.32,
    "max_energy": 1910,
    "regen_per_min": 17,
    "offline_cap_hours": 12,
    "passive_cap_per_hour": 597578,
    "airdrop_weight_per_1000": 4.03
  },
  {
    "level": 49,
    "xp_to_next": 31345,
    "cumulative_xp": 647794,
    "tap_reward": 6.57,
    "max_energy": 1940,
    "regen_per_min": 17,
    "offline_cap_hours": 12,
    "passive_cap_per_hour": 705142,
    "airdrop_weight_per_1000": 4.09
  },
  {
    "level": 50,
    "xp_to_next": 32263,
    "cumulative_xp": 680057,
    "tap_reward": 6.83,
    "max_energy": 1970,
    "regen_per_min": 17,
    "offline_cap_hours": 12,
    "passive_cap_per_hour": 832067,
    "airdrop_weight_per_1000": 4.15
  }
] as const;

export const ADN_FEATURE_UNLOCKS = [
  {
    "player_level": 1,
    "feature_system": "Starter Tap + 4 starter cards",
    "purpose": "Creates instant loop",
    "why_unlocks_here": "Immediate engagement",
    "reward_direction": "Fast ADN flow",
    "abuse_risk_notes": "No referral rewards yet",
    "ops_notes": "Tutorial only"
  },
  {
    "player_level": 2,
    "feature_system": "Daily bonus",
    "purpose": "First retention hook",
    "why_unlocks_here": "After first session understanding",
    "reward_direction": "Flat daily ADN",
    "abuse_risk_notes": "1 claim / 20h",
    "ops_notes": "Reset at UTC or local midnight"
  },
  {
    "player_level": 3,
    "feature_system": "Referral Hub",
    "purpose": "Introduce social growth",
    "why_unlocks_here": "User understands basic spend loop",
    "reward_direction": "Invite bonus + ADN",
    "abuse_risk_notes": "No self-referral",
    "ops_notes": "Track device/IP"
  },
  {
    "player_level": 5,
    "feature_system": "Streak multiplier",
    "purpose": "Second retention layer",
    "why_unlocks_here": "Daily habit now matters",
    "reward_direction": "+% daily reward",
    "abuse_risk_notes": "Break protection limited",
    "ops_notes": "Offer one rescue / week"
  },
  {
    "player_level": 6,
    "feature_system": "GPU / ASIC cards",
    "purpose": "Passive compounding begins",
    "why_unlocks_here": "Enough ADN to branch choices",
    "reward_direction": "Higher hourly ADN",
    "abuse_risk_notes": "Cap idle claim",
    "ops_notes": "Shift to passive build"
  },
  {
    "player_level": 8,
    "feature_system": "Referral Quest Chain",
    "purpose": "Quality referrals over raw invites",
    "why_unlocks_here": "User ready for objective-based social",
    "reward_direction": "ADN + airdrop weight",
    "abuse_risk_notes": "Only active referrals count",
    "ops_notes": "Quest engine online"
  },
  {
    "player_level": 10,
    "feature_system": "Creator Bounties",
    "purpose": "UGC-style growth",
    "why_unlocks_here": "Players seek faster progression",
    "reward_direction": "ADN + badge",
    "abuse_risk_notes": "Manual moderation if needed",
    "ops_notes": "Promo hooks"
  },
  {
    "player_level": 12,
    "feature_system": "Quantum Cooling / longer idle",
    "purpose": "Idle comfort upgrade",
    "why_unlocks_here": "Midgame pacing needs breathing room",
    "reward_direction": "More offline hours",
    "abuse_risk_notes": "Keep max cap in place",
    "ops_notes": "Good reactivation trigger"
  },
  {
    "player_level": 15,
    "feature_system": "Premium Market",
    "purpose": "Higher-value spend sink",
    "why_unlocks_here": "Monetization gate after habit formed",
    "reward_direction": "Access to advanced cards",
    "abuse_risk_notes": "Offer responsibly",
    "ops_notes": "Stars / premium hooks"
  },
  {
    "player_level": 18,
    "feature_system": "Guild Program",
    "purpose": "Social retention",
    "why_unlocks_here": "Enough economy depth for co-op",
    "reward_direction": "Guild quests",
    "abuse_risk_notes": "Limit alt-account farming",
    "ops_notes": "Seasonal races"
  },
  {
    "player_level": 22,
    "feature_system": "Auto-Tap Drones",
    "purpose": "Convenience power spike",
    "why_unlocks_here": "Midgame friction starts rising",
    "reward_direction": "More idle efficiency",
    "abuse_risk_notes": "Rate limit outputs",
    "ops_notes": "Server-side anti-cheat"
  },
  {
    "player_level": 25,
    "feature_system": "Seasonal Leaderboards",
    "purpose": "Status loop",
    "why_unlocks_here": "Core audience now invested",
    "reward_direction": "Cosmetic + weight rewards",
    "abuse_risk_notes": "Fraud filters mandatory",
    "ops_notes": "Manual fraud review"
  },
  {
    "player_level": 28,
    "feature_system": "Smart Missions",
    "purpose": "Personalized questing",
    "why_unlocks_here": "Player base now segmented",
    "reward_direction": "Targeted ADN",
    "abuse_risk_notes": "Avoid spam tasking",
    "ops_notes": "AI task engine can start here"
  },
  {
    "player_level": 30,
    "feature_system": "Whale Analytics",
    "purpose": "Late-game monetization lever",
    "why_unlocks_here": "Only relevant to advanced users",
    "reward_direction": "High-tier passive ADN",
    "abuse_risk_notes": "No pay-to-win hard lock",
    "ops_notes": "Use as premium sink"
  },
  {
    "player_level": 35,
    "feature_system": "Airdrop Claim Eligibility",
    "purpose": "Long-term aspiration",
    "why_unlocks_here": "Enough proof of quality activity",
    "reward_direction": "Claim window eligibility",
    "abuse_risk_notes": "KYC / review if needed",
    "ops_notes": "Snapshot-ready players"
  },
  {
    "player_level": 40,
    "feature_system": "Risk Review / Fast Lane Payouts",
    "purpose": "Separate trusted users",
    "why_unlocks_here": "Need ops tooling for payouts",
    "reward_direction": "Faster approvals",
    "abuse_risk_notes": "Do not auto-approve risky users",
    "ops_notes": "Ops thresholding"
  },
  {
    "player_level": 45,
    "feature_system": "Elite Exchange Cards",
    "purpose": "Endgame prestige loop",
    "why_unlocks_here": "Creates post-claim retention",
    "reward_direction": "Very high ADN/hr",
    "abuse_risk_notes": "Inflation monitored",
    "ops_notes": "Use limited drops"
  },
  {
    "player_level": 50,
    "feature_system": "Legend Tier + Prestige badge",
    "purpose": "Long horizon target",
    "why_unlocks_here": "Retains top 1-5% grinders",
    "reward_direction": "Cosmetic + weight bonus",
    "abuse_risk_notes": "No infinite loop reset by default",
    "ops_notes": "Season pass or prestige later"
  }
] as const;

export const ADN_UPGRADES = [
  {
    "upgrade_name": "Tap Engine",
    "id": "tap_engine",
    "category": "Mining",
    "unlock_level": 1,
    "base_cost": 50,
    "cost_growth": 1.34,
    "base_hourly_gain": 15,
    "gain_growth": 1.19,
    "max_tier": 15,
    "secondary_effect": "Tap multiplier",
    "effect_per_tier": "+1% every 5 tiers",
    "design_notes": "Starter efficiency anchor"
  },
  {
    "upgrade_name": "GPU Cluster",
    "id": "gpu_cluster",
    "category": "Mining",
    "unlock_level": 2,
    "base_cost": 120,
    "cost_growth": 1.35,
    "base_hourly_gain": 30,
    "gain_growth": 1.2,
    "max_tier": 15,
    "secondary_effect": "Energy restore",
    "effect_per_tier": "+5 energy/min every 5 tiers",
    "design_notes": "Smooth early passive"
  },
  {
    "upgrade_name": "Referral Hub",
    "id": "referral_hub",
    "category": "Community",
    "unlock_level": 3,
    "base_cost": 180,
    "cost_growth": 1.33,
    "base_hourly_gain": 40,
    "gain_growth": 1.18,
    "max_tier": 15,
    "secondary_effect": "Referral bonus",
    "effect_per_tier": "+1% referral reward per tier",
    "design_notes": "Quality social growth"
  },
  {
    "upgrade_name": "Liquidity Pool",
    "id": "liquidity_pool",
    "category": "Exchange",
    "unlock_level": 4,
    "base_cost": 220,
    "cost_growth": 1.34,
    "base_hourly_gain": 50,
    "gain_growth": 1.19,
    "max_tier": 15,
    "secondary_effect": "Offline yield",
    "effect_per_tier": "+0.5% idle income per tier",
    "design_notes": "Economy stabilizer"
  },
  {
    "upgrade_name": "Streak Vault",
    "id": "streak_vault",
    "category": "Community",
    "unlock_level": 5,
    "base_cost": 320,
    "cost_growth": 1.35,
    "base_hourly_gain": 70,
    "gain_growth": 1.19,
    "max_tier": 15,
    "secondary_effect": "Daily bonus",
    "effect_per_tier": "+2% daily bonus every 3 tiers",
    "design_notes": "Retention driver"
  },
  {
    "upgrade_name": "ASIC Vault",
    "id": "asic_vault",
    "category": "Mining",
    "unlock_level": 6,
    "base_cost": 400,
    "cost_growth": 1.37,
    "base_hourly_gain": 90,
    "gain_growth": 1.21,
    "max_tier": 15,
    "secondary_effect": "Tap crit chance",
    "effect_per_tier": "+0.3% crit chance per tier",
    "design_notes": "Midgame power step"
  },
  {
    "upgrade_name": "Swap Router",
    "id": "swap_router",
    "category": "Exchange",
    "unlock_level": 8,
    "base_cost": 600,
    "cost_growth": 1.36,
    "base_hourly_gain": 130,
    "gain_growth": 1.2,
    "max_tier": 15,
    "secondary_effect": "Market fee bonus",
    "effect_per_tier": "+0.4% claim conversion per tier",
    "design_notes": "Early finance card"
  },
  {
    "upgrade_name": "Creator Bounties",
    "id": "creator_bounties",
    "category": "Community",
    "unlock_level": 10,
    "base_cost": 850,
    "cost_growth": 1.35,
    "base_hourly_gain": 180,
    "gain_growth": 1.19,
    "max_tier": 15,
    "secondary_effect": "Quest reward",
    "effect_per_tier": "+1.5% mission reward per tier",
    "design_notes": "UGC/social engine"
  },
  {
    "upgrade_name": "Wallet Vault",
    "id": "wallet_vault",
    "category": "Security",
    "unlock_level": 11,
    "base_cost": 900,
    "cost_growth": 1.35,
    "base_hourly_gain": 170,
    "gain_growth": 1.18,
    "max_tier": 15,
    "secondary_effect": "Trust score",
    "effect_per_tier": "+0.5 trust per tier",
    "design_notes": "Supports fast-lane reviews"
  },
  {
    "upgrade_name": "Quantum Cooler",
    "id": "quantum_cooler",
    "category": "Mining",
    "unlock_level": 12,
    "base_cost": 1500,
    "cost_growth": 1.39,
    "base_hourly_gain": 260,
    "gain_growth": 1.22,
    "max_tier": 15,
    "secondary_effect": "Max energy",
    "effect_per_tier": "+15 max energy per tier",
    "design_notes": "Idle comfort"
  },
  {
    "upgrade_name": "AI Optimizer",
    "id": "ai_optimizer",
    "category": "Research",
    "unlock_level": 13,
    "base_cost": 1600,
    "cost_growth": 1.37,
    "base_hourly_gain": 320,
    "gain_growth": 1.21,
    "max_tier": 15,
    "secondary_effect": "Card synergy",
    "effect_per_tier": "+0.4% all hourly per tier",
    "design_notes": "Compounding driver"
  },
  {
    "upgrade_name": "Fee Engine",
    "id": "fee_engine",
    "category": "Exchange",
    "unlock_level": 14,
    "base_cost": 2500,
    "cost_growth": 1.38,
    "base_hourly_gain": 480,
    "gain_growth": 1.2,
    "max_tier": 15,
    "secondary_effect": "Spread capture",
    "effect_per_tier": "+0.5% passive cap per tier",
    "design_notes": "Late midgame finance"
  },
  {
    "upgrade_name": "Premium Market",
    "id": "premium_market",
    "category": "Exchange",
    "unlock_level": 15,
    "base_cost": 2800,
    "cost_growth": 1.39,
    "base_hourly_gain": 520,
    "gain_growth": 1.2,
    "max_tier": 15,
    "secondary_effect": "Premium offers",
    "effect_per_tier": "+1 premium slot every 5 tiers",
    "design_notes": "Monetization gate"
  },
  {
    "upgrade_name": "Guild Program",
    "id": "guild_program",
    "category": "Community",
    "unlock_level": 18,
    "base_cost": 3000,
    "cost_growth": 1.38,
    "base_hourly_gain": 600,
    "gain_growth": 1.19,
    "max_tier": 15,
    "secondary_effect": "Guild reward",
    "effect_per_tier": "+1% guild contribution value per tier",
    "design_notes": "Social lock-in"
  },
  {
    "upgrade_name": "Risk Oracle",
    "id": "risk_oracle",
    "category": "Security",
    "unlock_level": 19,
    "base_cost": 3500,
    "cost_growth": 1.37,
    "base_hourly_gain": 620,
    "gain_growth": 1.19,
    "max_tier": 15,
    "secondary_effect": "Fraud defense",
    "effect_per_tier": "+0.5 anti-farm rating per tier",
    "design_notes": "Ops health"
  },
  {
    "upgrade_name": "Market Maker",
    "id": "market_maker",
    "category": "Exchange",
    "unlock_level": 20,
    "base_cost": 7000,
    "cost_growth": 1.4,
    "base_hourly_gain": 1200,
    "gain_growth": 1.22,
    "max_tier": 15,
    "secondary_effect": "Liquidity depth",
    "effect_per_tier": "+0.6% market ROI per tier",
    "design_notes": "Big sink"
  },
  {
    "upgrade_name": "Auto-Tap Drones",
    "id": "auto_tap_drones",
    "category": "Research",
    "unlock_level": 22,
    "base_cost": 5200,
    "cost_growth": 1.39,
    "base_hourly_gain": 950,
    "gain_growth": 1.2,
    "max_tier": 15,
    "secondary_effect": "Idle taps",
    "effect_per_tier": "+0.5% idle taps per tier",
    "design_notes": "Convenience card"
  },
  {
    "upgrade_name": "Mission Center",
    "id": "mission_center",
    "category": "Community",
    "unlock_level": 24,
    "base_cost": 9500,
    "cost_growth": 1.4,
    "base_hourly_gain": 1650,
    "gain_growth": 1.2,
    "max_tier": 15,
    "secondary_effect": "Quest slots",
    "effect_per_tier": "+1 quest slot every 5 tiers",
    "design_notes": "Dynamic task depth"
  },
  {
    "upgrade_name": "Data Warehouse",
    "id": "data_warehouse",
    "category": "Research",
    "unlock_level": 26,
    "base_cost": 11000,
    "cost_growth": 1.41,
    "base_hourly_gain": 1800,
    "gain_growth": 1.21,
    "max_tier": 15,
    "secondary_effect": "Analytics boost",
    "effect_per_tier": "+0.5% all reward precision per tier",
    "design_notes": "Meta optimizer"
  },
  {
    "upgrade_name": "Whale Analytics",
    "id": "whale_analytics",
    "category": "Research",
    "unlock_level": 30,
    "base_cost": 22000,
    "cost_growth": 1.42,
    "base_hourly_gain": 3300,
    "gain_growth": 1.22,
    "max_tier": 15,
    "secondary_effect": "VIP targeting",
    "effect_per_tier": "+0.7% premium ROI per tier",
    "design_notes": "Endgame monetization"
  }
] as const;

export const ADN_REFERRAL_QUESTS = [
  {
    "chain": "Starter",
    "stage": 1,
    "unlock_level": 8,
    "task": "Invite 1 friend",
    "requirement_detail": "Referral joins via your code",
    "reward_adn": 300,
    "reward_weight": 10,
    "bonus_reward": "Bronze inviter badge",
    "completion_check": "Referral account created + tutorial done",
    "anti_abuse_rule": "No same device / same IP",
    "next_task_logic": "Open Stage 2"
  },
  {
    "chain": "Starter",
    "stage": 2,
    "unlock_level": 8,
    "task": "Make referral active",
    "requirement_detail": "Referral reaches Level 3",
    "reward_adn": 500,
    "reward_weight": 18,
    "bonus_reward": "1h 2x tap boost",
    "completion_check": "At least 2 sessions across 2 hours",
    "anti_abuse_rule": "Reject if account age < 30 min",
    "next_task_logic": "Open Stage 3"
  },
  {
    "chain": "Starter",
    "stage": 3,
    "unlock_level": 8,
    "task": "Referral earns ADN",
    "requirement_detail": "Referral earns 100 ADN",
    "reward_adn": 650,
    "reward_weight": 24,
    "bonus_reward": "Energy refill pack",
    "completion_check": "Server-side earnings check",
    "anti_abuse_rule": "No burst-only taps",
    "next_task_logic": "Open Stage 4"
  },
  {
    "chain": "Growth",
    "stage": 4,
    "unlock_level": 10,
    "task": "Bring 2 active referrals",
    "requirement_detail": "2 referrals reach Level 4",
    "reward_adn": 1200,
    "reward_weight": 40,
    "bonus_reward": "Creator bounty ticket",
    "completion_check": "Distinct device fingerprint",
    "anti_abuse_rule": "Max 1 reward / household unless reviewed",
    "next_task_logic": "Open Stage 5"
  },
  {
    "chain": "Growth",
    "stage": 5,
    "unlock_level": 10,
    "task": "Referral streak",
    "requirement_detail": "1 referral logs in 3 days in a row",
    "reward_adn": 1500,
    "reward_weight": 55,
    "bonus_reward": "Daily bonus +10% for 24h",
    "completion_check": "Consecutive UTC-day claims",
    "anti_abuse_rule": "No emulator clusters",
    "next_task_logic": "Open Stage 6"
  },
  {
    "chain": "Quality",
    "stage": 6,
    "unlock_level": 12,
    "task": "Referral taps consistently",
    "requirement_detail": "1 referral performs 200 valid taps",
    "reward_adn": 1800,
    "reward_weight": 70,
    "bonus_reward": "Quantum cooler shard",
    "completion_check": "Anti-cheat valid tap counter",
    "anti_abuse_rule": "Ignore locked users",
    "next_task_logic": "Open Stage 7"
  },
  {
    "chain": "Quality",
    "stage": 7,
    "unlock_level": 12,
    "task": "Idle progression",
    "requirement_detail": "1 referral claims offline earnings twice",
    "reward_adn": 2200,
    "reward_weight": 85,
    "bonus_reward": "Idle cap +0.5h for 24h",
    "completion_check": "Two separate offline claim timestamps",
    "anti_abuse_rule": "No script-like cadence",
    "next_task_logic": "Open Stage 8"
  },
  {
    "chain": "Scale",
    "stage": 8,
    "unlock_level": 15,
    "task": "Bring 3 engaged referrals",
    "requirement_detail": "3 referrals reach Level 6",
    "reward_adn": 3200,
    "reward_weight": 120,
    "bonus_reward": "Premium market ticket",
    "completion_check": "Level + session + spend depth",
    "anti_abuse_rule": "No self-invite graph loops",
    "next_task_logic": "Open Stage 9"
  },
  {
    "chain": "Scale",
    "stage": 9,
    "unlock_level": 15,
    "task": "Monetized social proof",
    "requirement_detail": "1 referral buys any premium boost",
    "reward_adn": 4000,
    "reward_weight": 160,
    "bonus_reward": "Premium chest",
    "completion_check": "Payment success webhook",
    "anti_abuse_rule": "No refunded / test payments",
    "next_task_logic": "Open Stage 10"
  },
  {
    "chain": "Retention",
    "stage": 10,
    "unlock_level": 18,
    "task": "Referral guild join",
    "requirement_detail": "2 referrals join or create guild",
    "reward_adn": 5200,
    "reward_weight": 210,
    "bonus_reward": "Guild booster",
    "completion_check": "Guild membership age > 24h",
    "anti_abuse_rule": "One guild loop only",
    "next_task_logic": "Open Stage 11"
  },
  {
    "chain": "Retention",
    "stage": 11,
    "unlock_level": 18,
    "task": "7-day referral retention",
    "requirement_detail": "1 referral active on day 7",
    "reward_adn": 7000,
    "reward_weight": 280,
    "bonus_reward": "7-day aura badge",
    "completion_check": "D1 + D3 + D7 activity",
    "anti_abuse_rule": "Filter suspicious clusters",
    "next_task_logic": "Open Stage 12"
  },
  {
    "chain": "Power",
    "stage": 12,
    "unlock_level": 22,
    "task": "High-value referral",
    "requirement_detail": "1 referral reaches Level 12",
    "reward_adn": 10000,
    "reward_weight": 380,
    "bonus_reward": "Auto-tap drone shard",
    "completion_check": "Progression verified server-side",
    "anti_abuse_rule": "No unusual spend spike",
    "next_task_logic": "Open Stage 13"
  },
  {
    "chain": "Power",
    "stage": 13,
    "unlock_level": 22,
    "task": "Referral economy contribution",
    "requirement_detail": "Referrals generate 10k combined ADN",
    "reward_adn": 12500,
    "reward_weight": 470,
    "bonus_reward": "Mission slot +1 for 24h",
    "completion_check": "Aggregate valid earn counter",
    "anti_abuse_rule": "Exclude banned users",
    "next_task_logic": "Open Stage 14"
  },
  {
    "chain": "Elite",
    "stage": 14,
    "unlock_level": 28,
    "task": "Elite social network",
    "requirement_detail": "5 referrals reach Level 8",
    "reward_adn": 18000,
    "reward_weight": 650,
    "bonus_reward": "Elite inviter badge",
    "completion_check": "All referrals distinct and active",
    "anti_abuse_rule": "Household cap review",
    "next_task_logic": "Open Stage 15"
  },
  {
    "chain": "Elite",
    "stage": 15,
    "unlock_level": 35,
    "task": "Claim-ready referral tree",
    "requirement_detail": "3 referrals become airdrop-eligible",
    "reward_adn": 30000,
    "reward_weight": 1000,
    "bonus_reward": "Fast-lane claim review",
    "completion_check": "Eligibility status true on 3 nodes",
    "anti_abuse_rule": "Manual review allowed",
    "next_task_logic": "Season reset / prestige quest"
  }
] as const;

export const ADN_MISSION_ENGINE = [
  {
    "player_segment": "New user",
    "primary_trigger": "Finished tutorial",
    "recommended_next_quest": "Buy 2 starter cards and claim daily bonus",
    "reason": "Teaches spend loop",
    "reward_mix": "70% ADN / 30% energy",
    "cooldown": "No cooldown",
    "when_to_avoid": "If user already L4+",
    "notes": "Keep copy short and encouraging",
    "ai_prompt_hint": null
  },
  {
    "player_segment": "Daily user",
    "primary_trigger": "Claimed daily bonus",
    "recommended_next_quest": "Play 3 short sessions today",
    "reason": "Build habit density",
    "reward_mix": "60% ADN / 40% streak XP",
    "cooldown": "12h",
    "when_to_avoid": "If session fatigue detected",
    "notes": "Push consistency over grind",
    "ai_prompt_hint": null
  },
  {
    "player_segment": "Referral-focused",
    "primary_trigger": "Completed referral stage",
    "recommended_next_quest": "Invite 1 more friend who reaches L3",
    "reason": "Extends social loop with quality filter",
    "reward_mix": "50% ADN / 50% weight",
    "cooldown": "18h",
    "when_to_avoid": "If suspicious network score high",
    "notes": "Reward active referrals only",
    "ai_prompt_hint": null
  },
  {
    "player_segment": "Cooling",
    "primary_trigger": "No login for 36h",
    "recommended_next_quest": "Return and finish 1 comeback mission",
    "reason": "Reactivation before churn hardens",
    "reward_mix": "40% ADN / 60% boost",
    "cooldown": "24h",
    "when_to_avoid": "If user opted out of notifications",
    "notes": "Use loss aversion copy",
    "ai_prompt_hint": null
  },
  {
    "player_segment": "Active grinder",
    "primary_trigger": "5+ sessions in 2 days",
    "recommended_next_quest": "Upgrade one midgame exchange card",
    "reason": "Convert activity into compounding",
    "reward_mix": "80% ADN / 20% badge",
    "cooldown": "8h",
    "when_to_avoid": "If user short on ADN",
    "notes": "Recommend best payback card",
    "ai_prompt_hint": null
  },
  {
    "player_segment": "Idle lover",
    "primary_trigger": "Multiple offline claims",
    "recommended_next_quest": "Increase idle cap via Liquidity Pool or Auto-Tap Drones",
    "reason": "Supports preferred playstyle",
    "reward_mix": "70% ADN / 30% idle boost",
    "cooldown": "12h",
    "when_to_avoid": "If passive cap already maxed",
    "notes": "Offer comfort not grind",
    "ai_prompt_hint": null
  },
  {
    "player_segment": "Mid spender",
    "primary_trigger": "Bought premium once",
    "recommended_next_quest": "Unlock Premium Market synergy combo",
    "reason": "Nudge repeat purchase without hard pressure",
    "reward_mix": "40% ADN / 30% premium chest / 30% weight",
    "cooldown": "24h",
    "when_to_avoid": "If refund risk or low trust",
    "notes": "Use soft-sell language",
    "ai_prompt_hint": null
  },
  {
    "player_segment": "Whale",
    "primary_trigger": "Bought premium multiple times",
    "recommended_next_quest": "Complete elite combo card upgrade",
    "reason": "Retain high-value users",
    "reward_mix": "30% ADN / 20% badge / 50% VIP perk",
    "cooldown": "36h",
    "when_to_avoid": "If progression cap reached",
    "notes": "Focus prestige and exclusivity",
    "ai_prompt_hint": null
  },
  {
    "player_segment": "Suspicious",
    "primary_trigger": "High fraud score",
    "recommended_next_quest": "Manual review or trust-restoring mission",
    "reason": "Reduce false positives and loss",
    "reward_mix": "Mostly non-economic rewards",
    "cooldown": "48h",
    "when_to_avoid": "If already banned",
    "notes": "Do not grant weight rewards",
    "ai_prompt_hint": null
  }
] as const;
